[tox]
min_version = 4.0
env_list =
    lint
    type
    ty
    pre-commit
    py3{12,13,14}
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    GitPython
commands =
    python -m pytest tests

[testenv:lint]
skip_install = true
deps = ruff~=0.16.0
commands =
    ruff check sereto

[testenv:type]
skip_install = false
deps = mypy
commands =
    mypy sereto

[testenv:ty]
skip_install = false
deps = ty>=0.0.55
commands =
    ty check sereto

[testenv:format]
skip_install = true
deps = ruff~=0.16.0
commands =
    ruff check --fix sereto
    ruff format sereto
    ruff check --fix tests
    ruff format tests

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands =
    pre-commit run --all-files

; Map Python versions from `setup-python` in Github Actions to Tox environments
; e.g. on Python 3.12, run the `py312`, `type`, and `lint` environments
[gh]
python =
    3.14 = py314
    3.13 = py313
    3.12 = py312, type, ty, lint
