name: Docker 🐳

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          sereto/sereto:latest
          sereto/sereto:${{ github.ref_name }}
